function data_excl = TRIALS_ARTIFACT_REJECT(data,params)

% INPUTS
% data: N channels x T time points, time series data
% params: struct generated by get_stim_timing.m which computes stimulation indices for each patient
%
% OUTPUTS:
% data_excl: data, but with channels set to NaN if artifact defining conditions are met:
% - max absolute value in any channel > 1e3 outside of the stim period


excl_channels = nanmax(abs(data(:,~ismember(1:size(data,2),params.stim_indices))')) > 1e3;   
data_excl = data;
data_excl(excl_channels,:) = nan;    